homeassistant:
  name: Dom
  latitude: 52.504266
  longitude: 16.733383
  elevation: 59
  unit_system: metric
  time_zone: Europe/Warsaw
  country: PL

default_config:

# Sieć hosta umożliwia wykrywanie urządzeń LAN; port zachowuje poprzedni adres panelu.
http:
  server_port: 9107

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

tts:
  - platform: google_translate
    language: pl

switch: !include switches.yaml
